### ISSUE TITLE
Character checklist

### ISSUE THREAD

**Issue by Tricky1975** [PhantasarProductions/The-Fairy-Tale-REVAMPED-for-Apollo#5]
- [x] Base startup
- [x] Jake Human + Fairy + Links
- [x] Ability Lists
    - [x] Jake (human)
    - [x] Jake (fairy)
    - [x] Marrilona
    - [x] Dandor
    - [x] Hando Stillor
    - [x] Krandar
    - (New Game+)
    - [x] Nostramantu (new game+ cutscene)
    - [x] Nostramantu (flashbacks)
    - [x] Feenalaria (awful dress)
    - [x] Feenalaria (cute dress) (this should just be a copy of the "awful dress" list, but I gotta take it all in order)
    - [x] Feenalaria (fairy)
- [x] Elemental resistances
- [x] Ailment resistances
- [x] Start equipment
- [x] Master field
- [x] END scriptout
- [x] Point linkups
- [x] Meta loading

**Comment by Tricky1975** [comment]
All over!
